using Microsoft.VisualBasic;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Diagnostics;
using System.Windows.Forms;
using System.Linq;
using System.Xml.Linq;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace LibraryManagementSystem.My.Resources
{

	//This class was auto-generated by the StronglyTypedResourceBuilder
	//class via a tool like ResGen or Visual Studio.
	//To add or remove a member, edit your .ResX file then rerun ResGen
	//with the /str option, or rebuild your VS project.
	///<summary>
	///  A strongly-typed resource class, for looking up localized strings, etc.
	///</summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Microsoft.VisualBasic.HideModuleNameAttribute()]
	static internal class Resources
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		///<summary>
		///  Returns the cached ResourceManager instance used by this class.
		///</summary>
		[System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		static internal global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibraryManagementSystem.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		///<summary>
		///  Overrides the current thread's CurrentUICulture property for all
		///  resource lookups using this strongly typed resource class.
		///</summary>
		[System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		static internal global::System.Globalization.CultureInfo Culture {
			get { return resourceCulture; }
			set { resourceCulture = value; }
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap _0088181331020_Color_Sky_Blue_SW_60X60 {
			get {
				object obj = ResourceManager.GetObject("0088181331020_Color_Sky-Blue_SW_60X60", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap _0088181331020_Color_Sky_Blue_SW_60X601 {
			get {
				object obj = ResourceManager.GetObject("0088181331020_Color_Sky-Blue_SW_60X601", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap _2 {
			get {
				object obj = ResourceManager.GetObject("2", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap _56928_256x256_courses_icon {
			get {
				object obj = ResourceManager.GetObject("56928-256x256-courses-icon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap _8314929977_28fd740070_z {
			get {
				object obj = ResourceManager.GetObject("8314929977_28fd740070_z", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap _8314929977_28fd740070_z1 {
			get {
				object obj = ResourceManager.GetObject("8314929977_28fd740070_z1", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap _924988520653134968 {
			get {
				object obj = ResourceManager.GetObject("924988520653134968", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap _9249885206531349681 {
			get {
				object obj = ResourceManager.GetObject("9249885206531349681", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap admissions_icon {
			get {
				object obj = ResourceManager.GetObject("admissions-icon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap admissions_icon1 {
			get {
				object obj = ResourceManager.GetObject("admissions-icon1", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap Background_books_entry {
			get {
				object obj = ResourceManager.GetObject("Background books entry", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap Background_books_entry1 {
			get {
				object obj = ResourceManager.GetObject("Background books entry1", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap Background_books_entry2 {
			get {
				object obj = ResourceManager.GetObject("Background books entry2", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap Background_books_entry3 {
			get {
				object obj = ResourceManager.GetObject("Background books entry3", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap books {
			get {
				object obj = ResourceManager.GetObject("books", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap calc {
			get {
				object obj = ResourceManager.GetObject("calc", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap calendar_year_icon {
			get {
				object obj = ResourceManager.GetObject("calendar_year_icon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap folder_home2 {
			get {
				object obj = ResourceManager.GetObject("folder_home2", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap folder_home21 {
			get {
				object obj = ResourceManager.GetObject("folder_home21", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap Graduate_Research_background_2 {
			get {
				object obj = ResourceManager.GetObject("Graduate-Research-background-2", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap images {
			get {
				object obj = ResourceManager.GetObject("images", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap images1 {
			get {
				object obj = ResourceManager.GetObject("images1", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap images2 {
			get {
				object obj = ResourceManager.GetObject("images2", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap images3 {
			get {
				object obj = ResourceManager.GetObject("images3", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap images4 {
			get {
				object obj = ResourceManager.GetObject("images4", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap images5 {
			get {
				object obj = ResourceManager.GetObject("images5", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap images51 {
			get {
				object obj = ResourceManager.GetObject("images51", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap images52 {
			get {
				object obj = ResourceManager.GetObject("images52", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap library_books_desks_bookshelf_objects_antique_2560x1600_wallpaper_wallpaperbeautiful_67 {
			get {
				object obj = ResourceManager.GetObject("library books desks bookshelf objects antique 2560x1600 wallpaper_wallpaperbeauti" + "ful_67", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap Log_Details {
			get {
				object obj = ResourceManager.GetObject("Log Details", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap login__2_ {
			get {
				object obj = ResourceManager.GetObject("login (2)", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap logout {
			get {
				object obj = ResourceManager.GetObject("logout", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap magazinesIcon {
			get {
				object obj = ResourceManager.GetObject("magazinesIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap mainfrm {
			get {
				object obj = ResourceManager.GetObject("mainfrm", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap MS_Word_2_icon1 {
			get {
				object obj = ResourceManager.GetObject("MS-Word-2-icon1", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap Notepad1 {
			get {
				object obj = ResourceManager.GetObject("Notepad1", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap photo {
			get {
				object obj = ResourceManager.GetObject("photo", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap Picture1 {
			get {
				object obj = ResourceManager.GetObject("Picture1", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap Picture11 {
			get {
				object obj = ResourceManager.GetObject("Picture11", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap registration_icon_up {
			get {
				object obj = ResourceManager.GetObject("registration_icon_up", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap registration_icon_up1 {
			get {
				object obj = ResourceManager.GetObject("registration_icon_up1", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap Researcher_resources_background2 {
			get {
				object obj = ResourceManager.GetObject("Researcher-resources-background2", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap stock_footage_all_is_written_in_the_books {
			get {
				object obj = ResourceManager.GetObject("stock-footage-all-is-written-in-the-books", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap stock_footage_all_is_written_in_the_books1 {
			get {
				object obj = ResourceManager.GetObject("stock-footage-all-is-written-in-the-books1", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap stock_footage_all_is_written_in_the_books2 {
			get {
				object obj = ResourceManager.GetObject("stock-footage-all-is-written-in-the-books2", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap stock_footage_library_table_full_of_books_isolated_on_white {
			get {
				object obj = ResourceManager.GetObject("stock-footage-library-table-full-of-books-isolated-on-white", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap supplierIcon2 {
			get {
				object obj = ResourceManager.GetObject("supplierIcon2", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap system_information_icon {
			get {
				object obj = ResourceManager.GetObject("system-information-icon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap System_Security_Card_icon {
			get {
				object obj = ResourceManager.GetObject("System-Security-Card-icon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap task_manager1 {
			get {
				object obj = ResourceManager.GetObject("task-manager1", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap textures_wallpapers_simple_and_beautifull_wood_texture_backgrounds {
			get {
				object obj = ResourceManager.GetObject("textures-wallpapers-simple-and-beautifull-wood-texture-backgrounds", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap textures_wallpapers_simple_and_beautifull_wood_texture_backgrounds1 {
			get {
				object obj = ResourceManager.GetObject("textures-wallpapers-simple-and-beautifull-wood-texture-backgrounds1", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap time_1920x1200 {
			get {
				object obj = ResourceManager.GetObject("time_1920x1200", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap top_image {
			get {
				object obj = ResourceManager.GetObject("top_image", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap url {
			get {
				object obj = ResourceManager.GetObject("url", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap User_icon {
			get {
				object obj = ResourceManager.GetObject("User-icon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap Wordpad_icon__Windows_7_ {
			get {
				object obj = ResourceManager.GetObject("Wordpad_icon_(Windows_7)", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap yellow_comment_bubbles_icon_culture_book2 {
			get {
				object obj = ResourceManager.GetObject("yellow-comment-bubbles-icon-culture-book2", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap yellow_comment_bubbles_icon_culture_book21 {
			get {
				object obj = ResourceManager.GetObject("yellow-comment-bubbles-icon-culture-book21", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		static internal System.Drawing.Bitmap yellow_comment_bubbles_icon_culture_book22 {
			get {
				object obj = ResourceManager.GetObject("yellow-comment-bubbles-icon-culture-book22", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}
	}
}
